pub struct Profeciency {
    pub abyssal: bool,
    pub acrobatics: bool,
    pub alchemists_supplies: bool,
    pub animal_handling: bool,
    pub arcana: bool,
    pub athletics: bool,
    pub bagpipes: bool,
    pub brewers_supplies: bool,
    pub calligraphers_supplies: bool,
    pub carpenters_tools: bool,
    pub cartographers_tools: bool,
    pub celestial: bool,
    pub cobblers_tools: bool,
    pub common: bool,
    pub common_sign_language: bool,
    pub cooks_utensils: bool,
    pub deception: bool,
    pub deep_speech: bool,
    pub dice_set: bool,
    pub disguise_kit: bool,
    pub draconic: bool,
    pub dragonchess_set: bool,
    pub druidic: bool,
    pub drum: bool,
    pub dulcimer: bool,
    pub dwarvish: bool,
    pub elvish: bool,
    pub flute: bool,
    pub forgery_kit: bool,
    pub giant: bool,
    pub glassblowers_tools: bool,
    pub gnomish: bool,
    pub goblin: bool,
    pub halfling: bool,
    pub heavy_armor: bool,
    pub herbalism_kit: bool,
    pub history: bool,
    pub horn: bool,
    pub improvised_weapon: bool,
    pub infernal: bool,
    pub insight: bool,
    pub intimidation: bool,
    pub investigation: bool,
    pub jewelers_tools: bool,
    pub land_vehicles: bool,
    pub leatherworkers_tools: bool,
    pub light_armor: bool,
    pub lute: bool,
    pub lyre: bool,
    pub martial_weapons: bool,
    pub masons_tools: bool,
    pub medicine: bool,
    pub medium_armor: bool,
    pub musket: bool,
    pub nature: bool,
    pub navigators_tools: bool,
    pub net: bool,
    pub orc: bool,
    pub painters_supplies: bool,
    pub pan_flute: bool,
    pub perception: bool,
    pub performance: bool,
    pub persuasion: bool,
    pub pistol: bool,
    pub playing_card_set: bool,
    pub poisoners_kit: bool,
    pub potters_tools: bool,
    pub primordial: bool,
    pub religion: bool,
    pub shawm: bool,
    pub shields: bool,
    pub simple_weapons: bool,
    pub sleight_of_hand: bool,
    pub smiths_tools: bool,
    pub stealth: bool,
    pub survival: bool,
    pub sylvan: bool,
    pub thieves_cant: bool,
    pub thieves_tools: bool,
    pub three_dragon_ante_set: bool,
    pub tinkers_tools: bool,
    pub unarmed_strike: bool,
    pub undercommon: bool,
    pub viol: bool,
    pub water_vehicles: bool,
    pub weavers_tools: bool,
    pub woodcarvers_tools: bool
}

impl Profeciency {
    pub fn new() -> Profeciency {
        Profeciency{
            abyssal: false,
            acrobatics: false,
            alchemists_supplies: false,
            animal_handling: false,
            arcana: false,
            athletics: false,
            bagpipes: false,
            brewers_supplies: false,
            calligraphers_supplies: false,
            carpenters_tools: false,
            cartographers_tools: false,
            celestial: false,
            cobblers_tools: false,
            common: false,
            common_sign_language: false,
            cooks_utensils: false,
            deception: false,
            deep_speech: false,
            dice_set: false,
            disguise_kit: false,
            draconic: false,
            dragonchess_set: false,
            druidic: false,
            drum: false,
            dulcimer: false,
            dwarvish: false,
            elvish: false,
            flute: false,
            forgery_kit: false,
            giant: false,
            glassblowers_tools: false,
            gnomish: false,
            goblin: false,
            halfling: false,
            heavy_armor: false,
            herbalism_kit: false,
            history: false,
            horn: false,
            improvised_weapon: false,
            infernal: false,
            insight: false,
            intimidation: false,
            investigation: false,
            jewelers_tools: false,
            land_vehicles: false,
            leatherworkers_tools: false,
            light_armor: false,
            lute: false,
            lyre: false,
            martial_weapons: false,
            masons_tools: false,
            medicine: false,
            medium_armor: false,
            musket: false,
            nature: false,
            navigators_tools: false,
            net: false,
            orc: false,
            painters_supplies: false,
            pan_flute: false,
            perception: false,
            performance: false,
            persuasion: false,
            pistol: false,
            playing_card_set: false,
            poisoners_kit: false,
            potters_tools: false,
            primordial: false,
            religion: false,
            shawm: false,
            shields: false,
            simple_weapons: false,
            sleight_of_hand: false,
            smiths_tools: false,
            stealth: false,
            survival: false,
            sylvan: false,
            thieves_cant: false,
            thieves_tools: false,
            three_dragon_ante_set: false,
            tinkers_tools: false,
            unarmed_strike: false,
            undercommon: false,
            viol: false,
            water_vehicles: false,
            weavers_tools: false,
            woodcarvers_tools: false
        }
    }
}
